name: Deploy RHEL Batch via Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::368017226728:role/GitHubActionsOidcRole
          aws-region: ap-northeast-1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install Ansible Galaxy collections
        run: |
          ansible-galaxy collection install -r requirements.yaml --force

      - name: Run Ansible playbook (Batch server)
        run: |
          ansible-playbook \
            -i inventories/prod/aws_ec2.yaml \
            playbooks/batch.yaml
        env:
          AWS_REGION: ap-northeast-1
          AWS_DEFAULT_REGION: ap-northeast-1
